project_id = "onrsmdqhkndbcjfuemqt"

[functions.transcribe-audio]
verify_jwt = false

[functions.generate-chord-voicing]
verify_jwt = false

[functions.import-song-url]
verify_jwt = false

[functions.transcribe-composition]
verify_jwt = false